### ISSUE TITLE
Mock S3 patching causes other uses of httplib2 to fail

### ISSUE THREAD

**Issue by wiltzius** [spulec/moto#303]
First of all, thanks for creating this library -- it's been extremely useful to us testing our app.

If a test is using the mock S3 instance and then tries to make an unrelated request with httplib2, that request fails with a BadStatusLine exception.

Here's a complete reduced example:

``` python
import unittest
import httplib2
from moto import mock_s3

class MyTestCase(unittest.TestCase):

  @classmethod
  def setUpClass(cls):
    mock_s3_obj = mock_s3()
    mock_s3_obj.start()

  def test_foo(self):
    http = httplib2.Http(timeout=60)
    http.follow_redirects = False
    http.request('https://google.com/', 'GET')
    return

if __name__ == '__main__':
  unittest.main()
```

the http.request line will raise a BadStatusLine exception deep in httplib somewhere.

I think ideally it should be possible to use Moto without it interfering with other services -- in our case, we want to mock S3 but use live Twilio for a certain integration test. Twilio's client, which uses httplib internally, is nonfunctional when s3 is mocked.

**Comment by spulec** [comment]
This is a bit of a known issue. See https://github.com/spulec/moto/issues/32 and https://github.com/gabrielfalcao/HTTPretty/issues/65.

I think there has been some recent progress on the issue in HTTPretty, but I think there unfortunately is still more work to do. I haven't tried it, but you can try using the fixes suggested in https://github.com/gabrielfalcao/HTTPretty/pull/216.

**Comment by wiltzius** [comment]
Ah yeah, I had not realized that #32 applied here.

For now we've worked around the issue by splitting our tests and not mocking S3 if we need any other live HTTP services. 

It looks like HTTPretty just merged that branch in, so maybe it's fixed with the latest. If I get a chance I'll give it a try -- are there any other known issues with newere HTTPretty versions? Moto is using 0.6.x which looks quite a bit older.

**Comment by spulec** [comment]
I'm not aware of any issues.

Moto just requires `httpretty>=0.6.1` so you should be able to upgrade. Please let me know if you see anything unusual though.

**Comment by porterjamesj** [comment]
just bumping to say that this still happens with the latest HTTPretty

**Comment by argos83** [comment]
Hi, this is still happening with `httpretty 0.8.14` and `moto 0.4.30` (the latest versions atm). Any updates on this issue?

Thanks

**Comment by spulec** [comment]
My understanding is that this is an issue with httpretty. Are you seeing otherwise?

**Comment by spulec** [comment]
This should no longer be an issue on the `master` branch. Please let me know if it is still happening.

**Comment by samfrances** [comment]
I'm still having this issue with moto 1.0.1 and httpretty 0.8.14.
