### ISSUE TITLE
boto3 support?

### ISSUE THREAD

**Issue by wmertens** [spulec/moto#348]
Any tips on how to mock boto3? I need it because you can't set up S3 notification with boto2...

**Comment by spulec** [comment]
In general, Moto doesn't rely on anything specific to Boto. It only mock AWS endpoints so there should be no issue with different boto versions. Is there a specific issue you are seeing?

**Comment by Kondou-ger** [comment]
I've tried out moto with boto3 and ran only into errors.
Here's a script breaking sqs and s3:

```
import boto3
import moto
import traceback


@moto.mock_sqs
def break_sqs_send():
        sqs = boto3.resource('sqs')
        queue = sqs.create_queue(QueueName="blah")
        queue.send_message(MessageBody="derp")


@moto.mock_sqs
def break_sqs_receive():
    sqs = boto3.resource('sqs')
    queue = sqs.create_queue(QueueName="blah")
    queue.receive_messages()

@moto.mock_s3
def break_s3_create():
    boto3.resource('s3').create_bucket(Bucket="blah")


break_it_all = [break_sqs_send, break_sqs_receive, break_s3_create]

for break_it in break_it_all:
    break_it_name = break_it.__qualname__
    print("Running " + break_it_name)
    try:
        break_it()
        print(break_it_name + " succeded")
    except Exception:
        traceback.print_exc()
    print("\n")
    print("-" * 80)
    print("\n")
```

Output (much has been truncated):
```
NotImplementedError: The send_message action has not been implemented
--------------------------------------------------------------------------------
NotImplementedError: The receive_message action has not been implemented
--------------------------------------------------------------------------------
botocore.exceptions.ClientError: An error occurred () when calling the CreateBucket operation: 
--------------------------------------------------------------------------------
```

**Comment by spulec** [comment]
Okay, I've done some work to ensure the basics should work with Boto3. Please feel free to open additional issues for more errors that you find.

**Comment by Kondou-ger** [comment]
For whatever reason the boto3-s3 test you added only works for us-east-1. It doesn't work for the zone I'm using (eu-central-1):

```python
import boto3
from moto import mock_s3

@mock_s3
def us_east():
    s3 = boto3.resource('s3', region_name='us-east-1')
    s3.create_bucket(Bucket="blah")
    s3.Object('blah', 'hello.txt').put(Body="some text")
    s3.Object('blah', 'hello.txt').get()['Body']

@mock_s3
def eu_central():
    s3 = boto3.resource('s3', region_name='eu-central-1')
    s3.create_bucket(Bucket="blah")
    s3.Object('blah', 'hello.txt').put(Body="some text")
    s3.Object('blah', 'hello.txt').get()['Body']

print("us")
us_east()
print("eu")
eu_central()
```

output
```
us
eu
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    eu_central()
  File "…/lib/python3.4/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "test.py", line 14, in eu_central
    s3.create_bucket(Bucket="blah")
  File "…/lib/python3.4/site-packages/boto3/resources/factory.py", line 344, in do_action
    response = action(self, *args, **kwargs)
  File "…/lib/python3.4/site-packages/boto3/resources/action.py", line 77, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "…/lib/python3.4/site-packages/botocore/client.py", line 269, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "…/lib/python3.4/site-packages/botocore/client.py", line 323, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred () when calling the CreateBucket operation:
```

**Comment by spulec** [comment]
From my testing, it seems to work for all regions except eu-central-1. It seems that eu-central-1 uses a [different endpoint format](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region). From what I am seeing, that region doesn't support buckets as subdomains so you will need to use the `s3bucket_path` decorator instead. It will also require another commit I just pushed to allow regions to be in the url for that service.

**Comment by vlcinsky** [comment]
I can confirm, that:

following regions work well with `@mock_s3()` and fail with `@mock_s3bucket_path`:

- us-east-1
- us-west-2
- us-west-1
- eu-west-1
- ap-southeast-1
- ap-southeast-2
- ap-northeast-1
- sa-east-1

following regions work well with `@mock_s3bucket_path` and fail with `@mock_s3`:

- eu-central-1

This covers all S3 related regions are published on http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by spulec** [comment]
Yes, this is a similar issue as my comment on #454. It seems that for most regions, boto3 (actually botocore) will try to use subdomain-style buckets instead of paths. The exception being bucket names with dots in the name where it will always use path-style buckets.

**Comment by spulec** [comment]
I have opened #471 as an attempt to combine the decorators into a single one that works with both calling formats. If someone could give that a test and confirm is works, that would be appreciated.

**Comment by tyrostone** [comment]
I am still experiencing this issue with us-west-2. I'm using moto version 0.4.23. I have tested using the test found in https://github.com/spulec/moto/blob/0df03ba409b4b3baf4e3492d84ac2d4d1d15a7a1/tests/test_s3/test_s3.py on lines 964-971.

```python
import boto3
from moto import mock_s3


@mock_s3
def moto_test_west():
    s3 = boto3.resource('s3', region_name='us-west-2')
    s3.create_bucket(Bucket="blah")
    s3.Object('blah', 'hello.txt').put(Body="some text")
    s3.Object('blah', 'hello.txt').get()['Body']

@mock_s3
def moto_test_eu():
    s3 = boto3.resource('s3', region_name='eu-central-1')
    s3.create_bucket(Bucket="blah")
    s3.Object('blah', 'hello.txt').put(Body="some text")
    s3.Object('blah', 'hello.txt').get()['Body']


print('eu')
moto_test_eu()
print('west')
moto_test_west()
```

Output:
```
eu
west
Traceback (most recent call last):
  File "mock_verabuild.py", line 23, in <module>
    moto_test_west()
  File "/Users/lstone/.virtualenvs/verabuild/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "mock_verabuild.py", line 8, in moto_test_west
    s3.create_bucket(Bucket="blah")
  File "/Users/lstone/.virtualenvs/verabuild/lib/python2.7/site-packages/boto3/resources/factory.py", line 455, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/lstone/.virtualenvs/verabuild/lib/python2.7/site-packages/boto3/resources/action.py", line 79, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/lstone/.virtualenvs/verabuild/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/lstone/.virtualenvs/verabuild/lib/python2.7/site-packages/botocore/client.py", line 407, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred () when calling the CreateBucket operation:
```

**Comment by andreis** [comment]
Happens here also. This fails:
```
============================================================= FAILURES =============================================================
________________________________________________________ TestAWS.test_fetch ________________________________________________________

self = <tests.test_aws.TestAWS testMethod=test_fetch>

    @mock_s3
    @mock_sqs
    def test_fetch(self):
        """Tests data fetching from SQS and S3"""
        # write an object to s3
        bucket = 'test_fetch_bucket'
        key = '123'
        s3 = boto3.client('s3')
>       s3.create_bucket(Bucket=bucket)

tests/test_aws.py:50: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.5/site-packages/botocore/client.py:228: in _api_call
    return self._make_api_call(operation_name, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <botocore.client.S3 object at 0x106d5d470>, operation_name = 'CreateBucket', api_params = {'Bucket': 'test_fetch_bucket'}

    def _make_api_call(self, operation_name, api_params):
        request_context = {}
        operation_model = self._service_model.operation_model(operation_name)
        request_dict = self._convert_to_request_dict(
            api_params, operation_model, context=request_context)
    
        handler, event_response = self.meta.events.emit_until_response(
            'before-call.{endpoint_prefix}.{operation_name}'.format(
                endpoint_prefix=self._service_model.endpoint_prefix,
                operation_name=operation_name),
            model=operation_model, params=request_dict,
            request_signer=self._request_signer, context=request_context)
    
        if event_response is not None:
            http, parsed_response = event_response
        else:
            http, parsed_response = self._endpoint.make_request(
                operation_model, request_dict)
    
        self.meta.events.emit(
            'after-call.{endpoint_prefix}.{operation_name}'.format(
                endpoint_prefix=self._service_model.endpoint_prefix,
                operation_name=operation_name),
            http_response=http, parsed=parsed_response,
            model=operation_model, context=request_context
        )
    
        if http.status_code >= 300:
>           raise ClientError(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred () when calling the CreateBucket operation:

/usr/local/lib/python3.5/site-packages/botocore/client.py:486: ClientError
================================================ 1 failed, 2 passed in 1.27 seconds ================================================
```

**Comment by andreis** [comment]
Can this be related? https://github.com/spulec/moto/issues/532

**Comment by spulec** [comment]
@tyrostone, that test is working for me locally against `HEAD`. Can you verify what version of boto3/botocore you are using?

**Comment by tyrostone** [comment]
@spulec 
boto3==1.2.3
botocore==1.3.26

**Comment by spulec** [comment]
I think this was fixed with https://github.com/spulec/moto/commit/15dc619fb23a484c908d4de9048e9b70783f5e21. Please let me know if not.
